version: '2'
services:
  web:
    image: registry.gitlab.com/viseo-digital-squads/welinktalent-server:dev
    links:
      - mongo
    environment:
      MONGODB_HOST: 'mongo'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
