version: '2'
services:
  web:
    image: registry.gitlab.com/viseo-digital-squads/welinktalent-server:dev
    fip: 209.177.90.14
    links:
      - mongo
    environment:
      HOST: '0.0.0.0'
      MONGODB_HOST: 'mongo'
    depends_on:
      - mongo
    ports:
      - "8080:80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
